### ISSUE TITLE
Submit a Kivy MD Kitchen Sink demo app to Apple App store and Google Play

### ISSUE THREAD

**Issue by GoBig87** [AndreMiras/KivyMD#8]
I noticed KivyMD is flying under the radar a bit and there are lots of complaints with Kivy's look and feel of the default UI and most people don't know what KivyMD is capable of.  It wouldn't be too much work to get the kitchen sink demo into Google and Apple's app store to help show case off what a material design app can look like in Kivy.  It would be great way to introduce kivy to potential users with out them having to go through the struggles of buildozer to get a working app and see what KivyMD is capable of. I wouldn't mind helping out getting it into the app stores as I have a mac and linux machine that can get builds into the app stores with the required credentials for each.  I just wouldn't want to step on peoples toes and submit their work as my own but it looks like nobody is actively maintaining it and not sure who should I get approval from?

**Comment by AndreMiras** [comment]
Yes having it on the store is a good idea, feel free to go ahead and do it :+1:

**Comment by GoBig87** [comment]
Got a release waiting for approval for Android and ios.   I named them "KivyMD Demo" in both app stores.  I'll provide links later once the app is approved and in the app stores.

**Comment by GoBig87** [comment]
For Android https://play.google.com/store/apps/details?id=org.kivymd.kivymd
  
ios might take a day or two.

**Comment by AndreMiras** [comment]
Awesome! Thanks

**Comment by GoBig87** [comment]
Well it looks like Apple wont allow demo apps...  So I don't think I'll be able to get it approved.  But I can upload it to test flight and if users want to try it out on an ios they can sign up for test flight and email me for access.

**Comment by cruor99** [comment]
Well you can have a public invite link for Testflight so that should solve it. You'd need to refresh the build every 90 days though.

**Comment by AndreMiras** [comment]
Pretty annoying, but in any case this Material Design so I don't think it targets iOS users anyway

**Comment by cruor99** [comment]
You'd be surprised! I find material design is pretty universal - it is very prevalent on the iOS ecosystem. Almost everything is based on material design, but with some custom flows per app. At least that's what it feels like for me. 

A suggestion might be a video-walkthrough of the various widgets? That would probably be equally valuable as an actual demo-app?

**Comment by AndreMiras** [comment]
Yes making a video is a pretty good idea too!
I remember I made a gif in the past to demo some apps e.g. https://github.com/kivy-garden/garden.zbarcam

**Comment by GoBig87** [comment]
https://testflight.apple.com/join/VxqQHYJN. I just made a test flight build that anyone can use.  I'll just have to update it every 90 days.

**Comment by AndreMiras** [comment]
Nice! Thanks for sharing!
I'll update some apps to run on F-Droid pretty soon. So I guess I could do it for KivyMD too :)

**Comment by quitegreensky** [comment]
> 
> 
> For Android https://play.google.com/store/apps/details?id=org.kivymd.kivymd
> 
> ios might take a day or two.

Hi ! @GoBig87 
Can you please provide the source code and also spec file of your project?
